In [1]:
import numpy as np
import scipy

### 2.1

In [2]:
# https://gist.github.com/hayesall/25d7ab12dcacf5988f577660c50d0bed

In [3]:
A = np.array([[3, 4, 1],
            [4, 6, 2],
            [1, 2, 3]])

In [4]:
B = np.array([1,2,3])
B = B.reshape(B.shape[0],1)

In [5]:
B.T.shape

(1, 3)

In [6]:
k = 4

In [7]:
C = np.array([[4, 1, -2],
            [1, 8, -1],
            [-2, -1, 6]])

In [8]:
def matrix_chain_order(p):
    """
    Matrix-Chain-Order given a list of integers corresponding to the dimensions
    of each pair of matrices forming a chain.
    :param list p: A list of integers.
    
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print(M)
    {(1, 1): 0, (2, 2): 0, (3, 3): 0, (1, 2): 160, (2, 3): 480, (1, 3): 208}
    >>> print(S)
    {(1, 2): 1, (2, 3): 2, (1, 3): 2}
    """
    s = {}
    m = {}
    n = len(p)
    
    for i in range(1, n):
        m[tuple([i, i])] = 0
    
    for l in range(2, n):
        for i in range(1, n - l + 1):
            j = i + l - 1
            m[tuple([i, j])] = float('inf')
            for k in range(i, j):
                q = m[tuple([i, k])] + m[tuple([k + 1, j])] + (p[i-1] * p[k] * p[j])
                if q < m[tuple([i, j])]:
                    m[tuple([i, j])] = q
                    s[tuple([i, j])] = k
    return m, s



class PrintString:
    def __init__(self):
        self.st = ''

        
# for chain of length <=9
def print_optimal_parens(s, i, j, ob):
    """
    Print the optimal parentheses according to the S-matrix computed by the
    matrix_chain_order function.
    :param dict s: A dictionary of tuples corresponding to the minimum k
                   values from each step of ``matrix_chain_order``.
    :param int i: Starting index.
    :param int j: End index.
    Example (continued from previous function):
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print_optimal_parens(S, 1, 3)
    ((A_1A_2)A_3)
    General form:

    >>> chain = [2, 20, 4, 6]
    >>> M, S = matrix_chain_order(chain)
    >>> print_optimal_parens(S, 1, len(S) - 1)
    ((A_1A_2)A_3)
    """

    if i == j:
        ob.st+="{}".format(i)
    else:
        ob.st+='('
        print_optimal_parens(s, i, s[tuple([i, j])], ob)
        print_optimal_parens(s, s[tuple([i, j])] + 1, j, ob)
        ob.st+=')'
       

In [9]:
cha = [B.T, A, k, C,B]
chain = []
const=1
for it in cha:
    if type(it)==type(np.zeros(3)):
        chain.append(it)
    else:
        const*=it

In [10]:
chain

[array([[1, 2, 3]]),
 array([[3, 4, 1],
        [4, 6, 2],
        [1, 2, 3]]),
 array([[ 4,  1, -2],
        [ 1,  8, -1],
        [-2, -1,  6]]),
 array([[1],
        [2],
        [3]])]

In [11]:
const

4

In [12]:
# check:
np.dot(np.dot(np.dot(chain[0],chain[1]),chain[2]),chain[3])*const

array([[2016]])

In [13]:
chain_dim=[chain[i].shape[0] for i in range(len(chain)-1)]

In [14]:
chain_dim.append(chain[-1].shape[0])
chain_dim.append(chain[-1].shape[1])

In [15]:
chain_dim

[1, 3, 3, 3, 1]

In [16]:
ch=[chain[i].shape for i in range(len(chain))]

In [17]:
ch

[(1, 3), (3, 3), (3, 3), (3, 1)]

In [18]:
M, S = matrix_chain_order(chain_dim)

In [19]:
M, S

({(1, 1): 0,
  (2, 2): 0,
  (3, 3): 0,
  (4, 4): 0,
  (1, 2): 9,
  (2, 3): 27,
  (3, 4): 9,
  (1, 3): 18,
  (2, 4): 18,
  (1, 4): 21},
 {(1, 2): 1, (2, 3): 2, (3, 4): 3, (1, 3): 2, (2, 4): 2, (1, 4): 1})

In [20]:
A=PrintString()

In [21]:
print_optimal_parens(S, 1, len(ch),A)

In [22]:
ans=A.st

In [23]:
ans

'(1(2(34)))'

In [24]:
count=0
i=0
stack = [ans[i]]
prev = ans[i]

while stack :
    tmp = stack[-1]
    if tmp==')':
        stack.pop()
        if count == 0:
            b=chain[int(stack.pop())-1]
            count+=1
        a=chain[int(stack.pop())-1]
        b=np.dot(a,b)
        stack.pop()
    else:
        stack.append(ans[i])
    if stack[-1]==')' and stack[-2]=='(':
        break
    if i < len(ans)-1:    
        i+=1

In [25]:
b*const 

array([[2016]])

### 2.2

In [26]:
a=np.array([[3,-1],[-1,2]])
np.linalg.inv(a)

array([[0.4, 0.2],
       [0.2, 0.6]])

In [27]:
np.linalg.det(a)

5.000000000000001

In [28]:
b=np.array([[2,0,1],[0,4,0],[1,0,2]])
np.linalg.inv(b)

array([[ 0.66666667,  0.        , -0.33333333],
       [ 0.        ,  0.25      ,  0.        ],
       [-0.33333333,  0.        ,  0.66666667]])

In [29]:
np.linalg.det(b)

11.999999999999995

### 2.3

In [30]:
np.linalg.matrix_rank(np.array([[1,3,4,-1,2],[4,1,-1,0,1],[-7,1,6,-1,-1]]))

3

### 2.4

In [31]:
def mat(k):
    return np.array([[1,-1,0],
                     [-1,1+k,-1],
                     [0,-1,1]])

In [32]:
def ra():
    for k in range(100):
        if np.linalg.matrix_rank(mat(k))==2:
            return k

In [33]:
Z = scipy.linalg.null_space(mat(ra()))

In [34]:
Z

array([[0.57735027],
       [0.57735027],
       [0.57735027]])

In [35]:
Z.T.dot(Z)

array([[1.]])

### 2.5

In [36]:
u = np.array([2,3,4])
v = np.array([1,2,3])

In [37]:
def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    """ Returns the angle in radians between vectors 'v1' and 'v2'::

            >>> angle_between((1, 0, 0), (0, 1, 0))
            1.5707963267948966
            >>> angle_between((1, 0, 0), (1, 0, 0))
            0.0
            >>> angle_between((1, 0, 0), (-1, 0, 0))
            3.141592653589793
    """
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))

#### a)

In [38]:
np.rad2deg(angle_between(u, v))

6.98249728791863

#### b)

In [39]:
def P(angle):
    return np.array([[1,0,0],
                     [0,np.cos(angle),np.sin(angle)],
                     [0,-np.sin(angle), np.cos(angle)]])

In [40]:
u2=np.dot(P(np.deg2rad(-30)), u)

In [41]:
u2

array([2.        , 0.59807621, 4.96410162])

In [42]:
v2=np.dot(P(np.deg2rad(-30)), v)

In [43]:
v2

array([1.        , 0.23205081, 3.59807621])

#### c)

In [44]:
np.rad2deg(angle_between(u2, v2))

6.982497287918682

### 2.6

#### a).

In [45]:
v = np.array([0,1,0])

In [46]:
alpha = 2/np.dot(v.T,v)

In [47]:
alpha

2.0

In [48]:
I = np.identity(3)

In [49]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
P=np.zeros((3,3))
for i in range(3):
    for j in range(3):
        P[i][j] = int(i==j)-alpha*v[i]*v[j]

In [51]:
a1=P.T

In [52]:
a2=np.linalg.inv(P)

In [53]:
np.all(a1==a2)

True

#### b).

In [54]:
u = np.array([0,3,0])

In [55]:
np.dot(P,u)

array([ 0., -3.,  0.])

### 2.7

#### a).

In [56]:
def P(theta):
    return np.array([[np.cos(theta), np.sin(theta)],
                     [-np.sin(theta),np.cos(theta)]])

In [57]:
tau=np.array([[10,-6],[-6,20]])

In [58]:
def tau_1(theta):
    return np.dot(np.dot(P(theta),tau),P(theta).T)

In [59]:
from scipy.optimize import fsolve

In [60]:
def func(theta):
    return (tau_1(theta)[1,0],tau_1(theta)[0,1])

In [61]:
for i in range(360):
    ans=func(i*np.pi/360)
    if abs(ans[0])<1e-1 and abs(ans[1])<1e-1:
        print(i)

50
230


In [62]:
tau_1(50*np.pi/360)

array([[ 7.18979529, -0.02650344],
       [-0.02650344, 22.81020471]])

In [63]:
tau_1(230*np.pi/360)

array([[22.81020471,  0.02650344],
       [ 0.02650344,  7.18979529]])

In [64]:
eig=np.linalg.eig(tau)

In [65]:
eig[0] # eigenvalue

array([ 7.18975032, 22.81024968])

In [66]:
eig[1] # eigenvectors

array([[-0.90558942,  0.4241554 ],
       [-0.4241554 , -0.90558942]])

#### b).

In [67]:
tau_11=np.array([[22.81024968,0],
                 [0,7.18975032]])

In [68]:
S=np.zeros((2,2))

In [69]:
for i in range(len(S)):
    for j in range(len(S[0])):
        S[i][j]=tau_11[i][j]-(tau_11[0][0]+tau_11[1][1])/2*int(i==j)

In [70]:
sigma_=0
for i in range(len(S)):
    for j in range(len(S[0])):
        sigma_+=S[i][j]*S[i][j]

In [71]:
sigma=np.sqrt(3/2*sigma_)

In [72]:
sigma

13.527749265558564

In [73]:
S=np.zeros((2,2))

In [74]:
for i in range(len(S)):
    for j in range(len(S[0])):
        S[i][j]=tau[i][j]-(tau[0][0]+tau[1][1])/2*int(i==j)

In [75]:
sigma_=0
for i in range(len(S)):
    for j in range(len(S[0])):
        sigma_+=S[i][j]*S[i][j]

In [76]:
sigma=np.sqrt(3/2*sigma_)

In [77]:
sigma

13.527749258468683

### 2.8

In [78]:
# q=[x1, x1+x2], where (x1, x2) a recoordinates of a point i.e. a vector. 

# if we subtract from q another vector e.g. [x1,x2] we must get a vector, but we would get
# [0, x1] and since [x1,x2] was any/every vector, we should have been able to get any vector 
# by subtracting this vector [x1,x2], but we only get [0,x1] which is in practicality 
# a scalar so we are not in vector space anymore, but by vector axioms we should have stayed
# in vector space when subtracting, but we did not, hence q is not a vector. 

### 2.9

In [79]:
from sympy import *

In [80]:
theta=Symbol('theta')

In [81]:
P=Matrix([[1,0,0],
          [0,cos(theta), sin(theta)],
          [0,-sin(theta),cos(theta)]])

In [82]:
P.T

Matrix([
[1,          0,           0],
[0, cos(theta), -sin(theta)],
[0, sin(theta),  cos(theta)]])

In [83]:
X_=[[0,0,0],
    [0,0,0],
    [0,0,0]]

In [84]:
for i in range(len(X_)):
    for j in range(len(X_)):
        X_[i][j]=str(int(i==j)) + ' + ' + 'du{}/dx{}'.format(i,j)

In [85]:
X=Matrix(X_)

In [86]:
eye(3)

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [87]:
e=1/2*simplify(X.T@X-eye(3))

In [88]:
e

Matrix([
[    0.5*(du1**2 + du2**2 - dx0**2 + (du0 + dx0)**2)/dx0**2, 0.5*(du0*(du0 + dx0) + du1*(du1 + dx1) + du2**2)/(dx0*dx1), 0.5*(du0*(du0 + dx0) + du1**2 + du2*(du2 + dx2))/(dx0*dx2)],
[0.5*(du0*(du0 + dx0) + du1*(du1 + dx1) + du2**2)/(dx0*dx1),     0.5*(du0**2 + du2**2 - dx1**2 + (du1 + dx1)**2)/dx1**2, 0.5*(du0**2 + du1*(du1 + dx1) + du2*(du2 + dx2))/(dx1*dx2)],
[0.5*(du0*(du0 + dx0) + du1**2 + du2*(du2 + dx2))/(dx0*dx2), 0.5*(du0**2 + du1*(du1 + dx1) + du2*(du2 + dx2))/(dx1*dx2),     0.5*(du0**2 + du1**2 - dx2**2 + (du2 + dx2)**2)/dx2**2]])

In [89]:
e.shape

(3, 3)

In [90]:
S=zeros(3,3)

In [91]:
S.shape

(3, 3)

In [92]:
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        S[i,j]=e[i,j]-(e[0,0]+e[1,1]+e[2,2])/3*int(i==j)

In [93]:
sigma_=0
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        sigma_+=S[i,j]*S[i,j]

In [94]:
sigma=sqrt(3/2*sigma_)

In [95]:
dx0, dx1,dx2,du0,du1,du2= symbols('dx0, dx1,dx2,du0,du1,du2')

In [96]:
sigma.simplify().subs({dx0:0.3,dx1:0.123, dx2:0.76, du0:0.34, du1:0.67, du2:0.56})

42.1169030949130

In [97]:
ans=simplify(P@e@P.T)

In [98]:
ans

Matrix([
[                                                                              1.0*(0.5*du0**2 + 1.0*du0*dx0 + 0.5*du1**2 + 0.5*du2**2)/dx0**2,                                                                                                                                                               0.5*(dx1*(du0*(du0 + dx0) + du1**2 + du2*(du2 + dx2))*sin(theta) + dx2*(du0*(du0 + dx0) + du1*(du1 + dx1) + du2**2)*cos(theta))/(dx0*dx1*dx2),                                                                                                                                                               0.5*(dx1*(du0*(du0 + dx0) + du1**2 + du2*(du2 + dx2))*cos(theta) - dx2*(du0*(du0 + dx0) + du1*(du1 + dx1) + du2**2)*sin(theta))/(dx0*dx1*dx2)],
[0.5*(dx1*(du0*(du0 + dx0) + du1**2 + du2*(du2 + dx2))*sin(theta) + dx2*(du0*(du0 + dx0) + du1*(du1 + dx1) + du2**2)*cos(theta))/(dx0*dx1*dx2), 0.5*(dx1*(dx1*(du0**2 + du1**2 - dx2**2 + (du2 + dx2)**2)*sin(theta) + dx2*(du0**2 + du1*(du1 + dx1)

In [99]:
ans.shape

(3, 3)

In [100]:
# see Definition 2.60

In [101]:
S=zeros(3,3)

In [102]:
S.shape

(3, 3)

In [103]:
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        S[i,j]=ans[i,j]-(ans[0,0]+ans[1,1]+ans[2,2])/3*int(i==j)

In [104]:
sigma_=0
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        sigma_+=S[i,j]*S[i,j]

In [105]:
sigma=sqrt(3/2*sigma_)

In [106]:
simplify(sigma).subs({dx0:0.3,dx1:0.123, dx2:0.76, du0:0.34, du1:0.67, du2:0.56})

42.116903094913*sqrt(1 - 9.91678213010411e-18*sin(4*theta))