In [1]:
import numpy as np
import scipy

### 2.1

In [2]:
# https://gist.github.com/hayesall/25d7ab12dcacf5988f577660c50d0bed

In [3]:
A = np.array([[3, 4, 1],
            [4, 6, 2],
            [1, 2, 3]])

In [4]:
B = np.array([1,2,3])
B = B.reshape(B.shape[0],1)

In [5]:
B.T.shape

(1, 3)

In [6]:
k = 4

In [7]:
C = np.array([[4, 1, -2],
            [1, 8, -1],
            [-2, -1, 6]])

In [8]:
def matrix_chain_order(p):
    """
    Matrix-Chain-Order given a list of integers corresponding to the dimensions
    of each pair of matrices forming a chain.
    :param list p: A list of integers.
    
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print(M)
    {(1, 1): 0, (2, 2): 0, (3, 3): 0, (1, 2): 160, (2, 3): 480, (1, 3): 208}
    >>> print(S)
    {(1, 2): 1, (2, 3): 2, (1, 3): 2}
    """
    s = {}
    m = {}
    n = len(p)
    
    for i in range(1, n):
        m[tuple([i, i])] = 0
    
    for l in range(2, n):
        for i in range(1, n - l + 1):
            j = i + l - 1
            m[tuple([i, j])] = float('inf')
            for k in range(i, j):
                q = m[tuple([i, k])] + m[tuple([k + 1, j])] + (p[i-1] * p[k] * p[j])
                if q < m[tuple([i, j])]:
                    m[tuple([i, j])] = q
                    s[tuple([i, j])] = k
    return m, s



class PrintString:
    def __init__(self):
        self.st = ''

        
# for chain of length <=9
def print_optimal_parens(s, i, j, ob):
    """
    Print the optimal parentheses according to the S-matrix computed by the
    matrix_chain_order function.
    :param dict s: A dictionary of tuples corresponding to the minimum k
                   values from each step of ``matrix_chain_order``.
    :param int i: Starting index.
    :param int j: End index.
    Example (continued from previous function):
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print_optimal_parens(S, 1, 3)
    ((A_1A_2)A_3)
    General form:

    >>> chain = [2, 20, 4, 6]
    >>> M, S = matrix_chain_order(chain)
    >>> print_optimal_parens(S, 1, len(S) - 1)
    ((A_1A_2)A_3)
    """

    if i == j:
        ob.st+="{}".format(i)
    else:
        ob.st+='('
        print_optimal_parens(s, i, s[tuple([i, j])], ob)
        print_optimal_parens(s, s[tuple([i, j])] + 1, j, ob)
        ob.st+=')'
       

In [9]:
cha = [B.T, A, k, C,B]
chain = []
const=1
for it in cha:
    if type(it)==type(np.zeros(3)):
        chain.append(it)
    else:
        const*=it

In [10]:
chain

[array([[1, 2, 3]]),
 array([[3, 4, 1],
        [4, 6, 2],
        [1, 2, 3]]),
 array([[ 4,  1, -2],
        [ 1,  8, -1],
        [-2, -1,  6]]),
 array([[1],
        [2],
        [3]])]

In [11]:
const

4

In [12]:
# check:
np.dot(np.dot(np.dot(chain[0],chain[1]),chain[2]),chain[3])*const

array([[2016]])

In [13]:
chain_dim=[chain[i].shape[0] for i in range(len(chain)-1)]

In [14]:
chain_dim.append(chain[-1].shape[0])
chain_dim.append(chain[-1].shape[1])

In [15]:
chain_dim

[1, 3, 3, 3, 1]

In [16]:
ch=[chain[i].shape for i in range(len(chain))]

In [17]:
ch

[(1, 3), (3, 3), (3, 3), (3, 1)]

In [18]:
M, S = matrix_chain_order(chain_dim)

In [19]:
M, S

({(1, 1): 0,
  (2, 2): 0,
  (3, 3): 0,
  (4, 4): 0,
  (1, 2): 9,
  (2, 3): 27,
  (3, 4): 9,
  (1, 3): 18,
  (2, 4): 18,
  (1, 4): 21},
 {(1, 2): 1, (2, 3): 2, (3, 4): 3, (1, 3): 2, (2, 4): 2, (1, 4): 1})

In [20]:
A=PrintString()

In [21]:
print_optimal_parens(S, 1, len(ch),A)

In [22]:
ans=A.st

In [23]:
ans

'(1(2(34)))'

In [24]:
count=0
i=0
stack = [ans[i]]
prev = ans[i]

while stack :
    tmp = stack[-1]
    if tmp==')':
        stack.pop()
        if count == 0:
            b=chain[int(stack.pop())-1]
            count+=1
        a=chain[int(stack.pop())-1]
        b=np.dot(a,b)
        stack.pop()
    else:
        stack.append(ans[i])
    if stack[-1]==')' and stack[-2]=='(':
        break
    if i < len(ans)-1:    
        i+=1

In [25]:
b*const 

array([[2016]])

### 2.2

In [26]:
a=np.array([[3,-1],[-1,2]])
np.linalg.inv(a)

array([[0.4, 0.2],
       [0.2, 0.6]])

In [27]:
np.linalg.det(a)

5.000000000000001

In [28]:
b=np.array([[2,0,1],[0,4,0],[1,0,2]])
np.linalg.inv(b)

array([[ 0.66666667,  0.        , -0.33333333],
       [ 0.        ,  0.25      ,  0.        ],
       [-0.33333333,  0.        ,  0.66666667]])

In [29]:
np.linalg.det(b)

11.999999999999995

### 2.3

In [30]:
np.linalg.matrix_rank(np.array([[1,3,4,-1,2],[4,1,-1,0,1],[-7,1,6,-1,-1]]))

3

### 2.4

In [31]:
def mat(k):
    return np.array([[1,-1,0],
                     [-1,1+k,-1],
                     [0,-1,1]])

In [32]:
def ra():
    for k in range(100):
        if np.linalg.matrix_rank(mat(k))==2:
            return k

In [33]:
Z = scipy.linalg.null_space(mat(ra()))

In [34]:
Z

array([[0.57735027],
       [0.57735027],
       [0.57735027]])

In [35]:
Z.T.dot(Z)

array([[1.]])

### 2.5

In [36]:
u = np.array([2,3,4])
v = np.array([1,2,3])

In [37]:
def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    """ Returns the angle in radians between vectors 'v1' and 'v2'::

            >>> angle_between((1, 0, 0), (0, 1, 0))
            1.5707963267948966
            >>> angle_between((1, 0, 0), (1, 0, 0))
            0.0
            >>> angle_between((1, 0, 0), (-1, 0, 0))
            3.141592653589793
    """
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))

#### a)

In [38]:
np.rad2deg(angle_between(u, v))

6.98249728791863

#### b)

In [39]:
def P(angle):
    return np.array([[1,0,0],
                     [0,np.cos(angle),np.sin(angle)],
                     [0,-np.sin(angle), np.cos(angle)]])

In [40]:
u2=np.dot(P(np.deg2rad(-30)), u)

In [41]:
u2

array([2.        , 0.59807621, 4.96410162])

In [42]:
v2=np.dot(P(np.deg2rad(-30)), v)

In [43]:
v2

array([1.        , 0.23205081, 3.59807621])

#### c)

In [44]:
np.rad2deg(angle_between(u2, v2))

6.982497287918682