In [1]:
# not validated solutions

In [2]:
import numpy as np
import scipy

### 2.1

In [3]:
# https://gist.github.com/hayesall/25d7ab12dcacf5988f577660c50d0bed

In [4]:
A = np.array([[3, 4, 1],
            [4, 6, 2],
            [1, 2, 3]])

In [5]:
B = np.array([1,2,3])
B = B.reshape(B.shape[0],1)

In [6]:
B.T.shape

(1, 3)

In [7]:
k = 4

In [8]:
C = np.array([[4, 1, -2],
            [1, 8, -1],
            [-2, -1, 6]])

In [9]:
def matrix_chain_order(p):
    """
    Matrix-Chain-Order given a list of integers corresponding to the dimensions
    of each pair of matrices forming a chain.
    :param list p: A list of integers.
    
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print(M)
    {(1, 1): 0, (2, 2): 0, (3, 3): 0, (1, 2): 160, (2, 3): 480, (1, 3): 208}
    >>> print(S)
    {(1, 2): 1, (2, 3): 2, (1, 3): 2}
    """
    s = {}
    m = {}
    n = len(p)
    
    for i in range(1, n):
        m[tuple([i, i])] = 0
    
    for l in range(2, n):
        for i in range(1, n - l + 1):
            j = i + l - 1
            m[tuple([i, j])] = float('inf')
            for k in range(i, j):
                q = m[tuple([i, k])] + m[tuple([k + 1, j])] + (p[i-1] * p[k] * p[j])
                if q < m[tuple([i, j])]:
                    m[tuple([i, j])] = q
                    s[tuple([i, j])] = k
    return m, s



class PrintString:
    def __init__(self):
        self.st = ''

        
# for chain of length <=9
def print_optimal_parens(s, i, j, ob):
    """
    Print the optimal parentheses according to the S-matrix computed by the
    matrix_chain_order function.
    :param dict s: A dictionary of tuples corresponding to the minimum k
                   values from each step of ``matrix_chain_order``.
    :param int i: Starting index.
    :param int j: End index.
    Example (continued from previous function):
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print_optimal_parens(S, 1, 3)
    ((A_1A_2)A_3)
    General form:

    >>> chain = [2, 20, 4, 6]
    >>> M, S = matrix_chain_order(chain)
    >>> print_optimal_parens(S, 1, len(S) - 1)
    ((A_1A_2)A_3)
    """

    if i == j:
        ob.st+="{}".format(i)
    else:
        ob.st+='('
        print_optimal_parens(s, i, s[tuple([i, j])], ob)
        print_optimal_parens(s, s[tuple([i, j])] + 1, j, ob)
        ob.st+=')'
       

In [10]:
cha = [B.T, A, k, C,B]
chain = []
const=1
for it in cha:
    if type(it)==type(np.zeros(3)):
        chain.append(it)
    else:
        const*=it

In [11]:
chain

[array([[1, 2, 3]]),
 array([[3, 4, 1],
        [4, 6, 2],
        [1, 2, 3]]),
 array([[ 4,  1, -2],
        [ 1,  8, -1],
        [-2, -1,  6]]),
 array([[1],
        [2],
        [3]])]

In [12]:
const

4

In [13]:
# check:
np.dot(np.dot(np.dot(chain[0],chain[1]),chain[2]),chain[3])*const

array([[2016]])

In [14]:
chain_dim=[chain[i].shape[0] for i in range(len(chain)-1)]

In [15]:
chain_dim.append(chain[-1].shape[0])
chain_dim.append(chain[-1].shape[1])

In [16]:
chain_dim

[1, 3, 3, 3, 1]

In [17]:
ch=[chain[i].shape for i in range(len(chain))]

In [18]:
ch

[(1, 3), (3, 3), (3, 3), (3, 1)]

In [19]:
M, S = matrix_chain_order(chain_dim)

In [20]:
M, S

({(1, 1): 0,
  (2, 2): 0,
  (3, 3): 0,
  (4, 4): 0,
  (1, 2): 9,
  (2, 3): 27,
  (3, 4): 9,
  (1, 3): 18,
  (2, 4): 18,
  (1, 4): 21},
 {(1, 2): 1, (2, 3): 2, (3, 4): 3, (1, 3): 2, (2, 4): 2, (1, 4): 1})

In [21]:
A=PrintString()

In [22]:
print_optimal_parens(S, 1, len(ch),A)

In [23]:
ans=A.st

In [24]:
ans

'(1(2(34)))'

In [25]:
count=0
i=0
stack = [ans[i]]
prev = ans[i]

while stack :
    tmp = stack[-1]
    if tmp==')':
        stack.pop()
        if count == 0:
            b=chain[int(stack.pop())-1]
            count+=1
        a=chain[int(stack.pop())-1]
        b=np.dot(a,b)
        stack.pop()
    else:
        stack.append(ans[i])
    if stack[-1]==')' and stack[-2]=='(':
        break
    if i < len(ans)-1:    
        i+=1

In [26]:
b*const 

array([[2016]])

### 2.2

In [27]:
a=np.array([[3,-1],[-1,2]])
np.linalg.inv(a)

array([[0.4, 0.2],
       [0.2, 0.6]])

In [28]:
np.linalg.det(a)

5.000000000000001

In [29]:
b=np.array([[2,0,1],[0,4,0],[1,0,2]])
np.linalg.inv(b)

array([[ 0.66666667,  0.        , -0.33333333],
       [ 0.        ,  0.25      ,  0.        ],
       [-0.33333333,  0.        ,  0.66666667]])

In [30]:
np.linalg.det(b)

11.999999999999995

### 2.3

In [31]:
np.linalg.matrix_rank(np.array([[1,3,4,-1,2],[4,1,-1,0,1],[-7,1,6,-1,-1]]))

3

### 2.4

In [32]:
def mat(k):
    return np.array([[1,-1,0],
                     [-1,1+k,-1],
                     [0,-1,1]])

In [33]:
def ra():
    for k in range(100):
        if np.linalg.matrix_rank(mat(k))==2:
            return k

In [34]:
Z = scipy.linalg.null_space(mat(ra()))

In [35]:
Z

array([[0.57735027],
       [0.57735027],
       [0.57735027]])

In [36]:
Z.T.dot(Z)

array([[1.]])

### 2.5

In [37]:
u = np.array([2,3,4])
v = np.array([1,2,3])

In [38]:
def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    """ Returns the angle in radians between vectors 'v1' and 'v2'::

            >>> angle_between((1, 0, 0), (0, 1, 0))
            1.5707963267948966
            >>> angle_between((1, 0, 0), (1, 0, 0))
            0.0
            >>> angle_between((1, 0, 0), (-1, 0, 0))
            3.141592653589793
    """
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))

#### a)

In [39]:
np.rad2deg(angle_between(u, v))

6.98249728791863

#### b)

In [40]:
def P(angle):
    return np.array([[1,0,0],
                     [0,np.cos(angle),np.sin(angle)],
                     [0,-np.sin(angle), np.cos(angle)]])

In [41]:
u2=np.dot(P(np.deg2rad(-30)), u)

In [42]:
u2

array([2.        , 0.59807621, 4.96410162])

In [43]:
v2=np.dot(P(np.deg2rad(-30)), v)

In [44]:
v2

array([1.        , 0.23205081, 3.59807621])

#### c)

In [45]:
np.rad2deg(angle_between(u2, v2))

6.982497287918682

### 2.6

#### a).

In [46]:
v = np.array([0,1,0])

In [47]:
alpha = 2/np.dot(v.T,v)

In [48]:
alpha

2.0

In [49]:
I = np.identity(3)

In [50]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
P=np.zeros((3,3))
for i in range(3):
    for j in range(3):
        P[i][j] = int(i==j)-alpha*v[i]*v[j]

In [52]:
a1=P.T

In [53]:
a2=np.linalg.inv(P)

In [54]:
np.all(a1==a2)

True

#### b).

In [55]:
u = np.array([0,3,0])

In [56]:
np.dot(P,u)

array([ 0., -3.,  0.])

### 2.7

#### a).

In [57]:
def P(theta):
    return np.array([[np.cos(theta), np.sin(theta)],
                     [-np.sin(theta),np.cos(theta)]])

In [58]:
tau=np.array([[10,-6],[-6,20]])

In [59]:
def tau_1(theta):
    return np.dot(np.dot(P(theta),tau),P(theta).T)

In [60]:
from scipy.optimize import fsolve

In [61]:
def func(theta):
    return (tau_1(theta)[1,0],tau_1(theta)[0,1])

In [62]:
for i in range(360):
    ans=func(i*np.pi/360)
    if abs(ans[0])<1e-1 and abs(ans[1])<1e-1:
        print(i)

50
230


In [63]:
tau_1(50*np.pi/360)

array([[ 7.18979529, -0.02650344],
       [-0.02650344, 22.81020471]])

In [64]:
tau_1(230*np.pi/360)

array([[22.81020471,  0.02650344],
       [ 0.02650344,  7.18979529]])

In [65]:
eig=np.linalg.eig(tau)

In [66]:
eig[0] # eigenvalue

array([ 7.18975032, 22.81024968])

In [67]:
eig[1] # eigenvectors

array([[-0.90558942,  0.4241554 ],
       [-0.4241554 , -0.90558942]])

#### b).

In [68]:
tau_11=np.array([[22.81024968,0],
                 [0,7.18975032]])

In [69]:
S=np.zeros((2,2))

In [70]:
for i in range(len(S)):
    for j in range(len(S[0])):
        S[i][j]=tau_11[i][j]-(tau_11[0][0]+tau_11[1][1])/2*int(i==j)

In [71]:
sigma_=0
for i in range(len(S)):
    for j in range(len(S[0])):
        sigma_+=S[i][j]*S[i][j]

In [72]:
sigma=np.sqrt(3/2*sigma_)

In [73]:
sigma

13.527749265558564

In [74]:
S=np.zeros((2,2))

In [75]:
for i in range(len(S)):
    for j in range(len(S[0])):
        S[i][j]=tau[i][j]-(tau[0][0]+tau[1][1])/2*int(i==j)

In [76]:
sigma_=0
for i in range(len(S)):
    for j in range(len(S[0])):
        sigma_+=S[i][j]*S[i][j]

In [77]:
sigma=np.sqrt(3/2*sigma_)

In [78]:
sigma

13.527749258468683

### 2.8

In [79]:
# q=[x1, x1+x2], where (x1, x2) a recoordinates of a point i.e. a vector. 

# if we subtract from q another vector e.g. [x1,x2] we must get a vector, but we would get
# [0, x1] and since [x1,x2] was any/every vector, we should have been able to get any vector 
# by subtracting this vector [x1,x2], but we only get [0,x1] which is in practicality 
# a scalar so we are not in vector space anymore, but by vector axioms we should have stayed
# in vector space when subtracting, but we did not, hence q is not a vector. 

### 2.9

In [80]:
from sympy import *

In [81]:
theta=Symbol('theta')

In [82]:
P=Matrix([[1,0,0],
          [0,cos(theta), sin(theta)],
          [0,-sin(theta),cos(theta)]])

In [83]:
P.T

Matrix([
[1,          0,           0],
[0, cos(theta), -sin(theta)],
[0, sin(theta),  cos(theta)]])

In [84]:
X_=[[0,0,0],
    [0,0,0],
    [0,0,0]]

In [85]:
x0,x1,x2= symbols('x0, x1,x2')

In [86]:
u0,u1,u2=Function('u0')(x0, x1,x2),Function('u1')(x0, x1,x2),Function('u2')(x0, x1,x2)

In [87]:
for i in range(len(X_)):
    for j in range(len(X_)):
        X_[i][j]=int(i==j)  + diff(eval('u{}'.format(i)),eval('x{}'.format(j)))

In [88]:
X = Matrix(X_)

In [89]:
X

Matrix([
[Derivative(u0(x0, x1, x2), x0) + 1,     Derivative(u0(x0, x1, x2), x1),     Derivative(u0(x0, x1, x2), x2)],
[    Derivative(u1(x0, x1, x2), x0), Derivative(u1(x0, x1, x2), x1) + 1,     Derivative(u1(x0, x1, x2), x2)],
[    Derivative(u2(x0, x1, x2), x0),     Derivative(u2(x0, x1, x2), x1), Derivative(u2(x0, x1, x2), x2) + 1]])

In [90]:
eye(3)

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [91]:
e=1/2*simplify(X.T@X-eye(3))

In [92]:
e

Matrix([
[                                                                                    0.5*(Derivative(u0(x0, x1, x2), x0) + 1)**2 + 0.5*Derivative(u1(x0, x1, x2), x0)**2 + 0.5*Derivative(u2(x0, x1, x2), x0)**2 - 0.5, 0.5*(Derivative(u0(x0, x1, x2), x0) + 1)*Derivative(u0(x0, x1, x2), x1) + 0.5*(Derivative(u1(x0, x1, x2), x1) + 1)*Derivative(u1(x0, x1, x2), x0) + 0.5*Derivative(u2(x0, x1, x2), x0)*Derivative(u2(x0, x1, x2), x1), 0.5*(Derivative(u0(x0, x1, x2), x0) + 1)*Derivative(u0(x0, x1, x2), x2) + 0.5*(Derivative(u2(x0, x1, x2), x2) + 1)*Derivative(u2(x0, x1, x2), x0) + 0.5*Derivative(u1(x0, x1, x2), x0)*Derivative(u1(x0, x1, x2), x2)],
[0.5*(Derivative(u0(x0, x1, x2), x0) + 1)*Derivative(u0(x0, x1, x2), x1) + 0.5*(Derivative(u1(x0, x1, x2), x1) + 1)*Derivative(u1(x0, x1, x2), x0) + 0.5*Derivative(u2(x0, x1, x2), x0)*Derivative(u2(x0, x1, x2), x1),                                                                                     0.5*(Derivative(u1(x0, x1, x2), x1) + 1)**2 

In [93]:
e.shape

(3, 3)

In [94]:
S=zeros(3,3)

In [95]:
S.shape

(3, 3)

In [96]:
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        S[i,j]=e[i,j]-(e[0,0]+e[1,1]+e[2,2])/3*int(i==j)

In [97]:
sigma_=0
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        sigma_+=S[i,j]*S[i,j]

In [98]:
sigma=sqrt(3/2*sigma_)

In [99]:
# For example:
sigma.subs({u0:x0+x1+x2,
            u1:x0*x1*x2, 
            u2:x1*x2+x2*x0+x0*x1}).simplify().subs({x0:0.23,x1:1.56,x2:0.78})

10.5075934583603

In [100]:
ans=simplify(P@e@P.T)

In [101]:
ans

Matrix([
[                                                                                                                                                                                                                                                                                                                       0.5*(Derivative(u0(x0, x1, x2), x0) + 1)**2 + 0.5*Derivative(u1(x0, x1, x2), x0)**2 + 0.5*Derivative(u2(x0, x1, x2), x0)**2 - 0.5,                                                                                                                                                                                                                                                                                                  0.5*((Derivative(u0(x0, x1, x2), x0) + 1)*Derivative(u0(x0, x1, x2), x1) + (Derivative(u1(x0, x1, x2), x1) + 1)*Derivative(u1(x0, x1, x2), x0) + Derivative(u2(x0, x1, x2), x0)*Derivative(u2(x0, x1, x2), x1))*cos(theta) + 0.5*((Derivative(u0(x0, x1, x2), x0) +

In [102]:
ans.shape

(3, 3)

In [103]:
# see Definition 2.60

In [104]:
S=zeros(3,3)

In [105]:
S.shape

(3, 3)

In [106]:
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        S[i,j]=ans[i,j]-(ans[0,0]+ans[1,1]+ans[2,2])/3*int(i==j)

In [107]:
sigma_=0
for i in range(S.shape[0]):
    for j in range(S.shape[1]):
        sigma_+=S[i,j]*S[i,j]

In [108]:
sigma1 = sqrt(3/2*sigma_)

In [109]:
simplify(sigma1).subs({u0:x0+x1+x2,
                        u1:x0*x1*x2, 
                        u2:x1*x2+x2*x0+x0*x1}).simplify().subs({x0:0.23,x1:1.56,x2:0.78})

10.5075934583603*sqrt(1.21593375634644e-18*sin(4*theta) + 1)

In [110]:
# or in general for finite space domain and finite displacements
(sigma**2-sigma1**2).simplify() # ~ 0

-1.11022302462516e-16*sin(4*theta)*Derivative(u1(x0, x1, x2), x1)**2*Derivative(u1(x0, x1, x2), x2) + 1.11022302462516e-16*sin(4*theta)*Derivative(u2(x0, x1, x2), x1)*Derivative(u2(x0, x1, x2), x2)**2 + 6.16297582203915e-33*Derivative(u0(x0, x1, x2), x0) + 6.16297582203915e-33*Derivative(u1(x0, x1, x2), x1) + 6.16297582203915e-33*Derivative(u2(x0, x1, x2), x2) + 1.54074395550979e-33

### 2.10

#### a).

In [111]:
E,v = 2.1e9, 0.3

In [112]:
lambda_ = (E*v)/((1+v)*(1-2*v))

In [113]:
lambda_

1211538461.5384614

In [114]:
mu_ = E/(2*(1+v))

In [115]:
mu_

807692307.6923077

In [116]:
C=np.zeros((3,3,3,3))

In [117]:
for i in range(3):
    for j in range(3):
        for r in range(3):
            for s in range(3):
                C[i][j][r][s]=lambda_*int(i==j)*int(r==s)+mu_*(int(i==r)*int(j==s)+int(i==s)*int(j==r))

In [118]:
S=np.zeros((3,3,3,3))

In [119]:
for i in range(3):
    for j in range(3):
        for r in range(3):
            for s in range(3):
                S[i][j][r][s]=C[i][j][r][s]-(C[0][0][0][0]+C[1][1][1][1]+C[2][2][2][2])/3*int(i==j==r==s)

In [120]:
sigma_=0
for i in range(3):
    for j in range(3):
        for r in range(3):
            for s in range(3):
                sigma_+=S[i,j,r,s]*S[i,j,r,s]

In [121]:
sigma=np.sqrt(3/2*sigma_)

In [122]:
sigma

4995301046.421395

In [123]:
theta=30.1*np.pi/360

In [124]:
P=np.array([[1,0,0],
          [0,np.cos(theta), np.sin(theta)],
          [0,-np.sin(theta),np.cos(theta)]])

In [125]:
C1=np.zeros((3,3,3,3))

In [126]:
for i in range(3):
    for j in range(3):
        for r in range(3):
            for s in range(3):
                tmp=0
                for m in range(3):
                    for n in range(3):
                        for k in range(3):
                            for l in range(3):
                                tmp += P[i][m]*P[j][n]*P[r][k]*P[s][l]*C[m][n][k][l]
                C1[i][j][r][s] = tmp               

In [127]:
S1=np.zeros((3,3,3,3))

In [128]:
for i in range(3):
    for j in range(3):
        for r in range(3):
            for s in range(3):
                S1[i][j][r][s]=C1[i][j][r][s]-(C1[0][0][0][0]+C1[1][1][1][1]+C1[2][2][2][2])/3*int(i==j==r==s)

In [129]:
sigma_=0
for i in range(3):
    for j in range(3):
        for r in range(3):
            for s in range(3):
                sigma_ += S1[i,j,r,s]*S1[i,j,r,s]

In [130]:
sigma1=np.sqrt(3/2*sigma_)

In [131]:
sigma1

4995301046.421395

#### b).

Check e.g.: https://serc.carleton.edu/NAGTWorkshops/mineralogy/mineral_physics/tensors.html

#### c).

In [132]:
D=E/(1-v**2)*np.array([[1,v,0],
                       [v,1,0],
                       [0,0,(1-v)/2]])

In [133]:
D

array([[2.30769231e+09, 6.92307692e+08, 0.00000000e+00],
       [6.92307692e+08, 2.30769231e+09, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.07692308e+08]])

In [134]:
eig=np.linalg.eig(D)
D1_v=eig[0]

In [135]:
D1=np.diag(D1_v)

In [136]:
D1

array([[3.00000000e+09, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.61538462e+09, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.07692308e+08]])

In [137]:
eig[1]@D1@np.linalg.inv(eig[1])

array([[2.30769231e+09, 6.92307692e+08, 0.00000000e+00],
       [6.92307692e+08, 2.30769231e+09, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.07692308e+08]])

In [138]:
eig[1]@D1@eig[1].T

array([[2.30769231e+09, 6.92307692e+08, 0.00000000e+00],
       [6.92307692e+08, 2.30769231e+09, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.07692308e+08]])

In [139]:
np.linalg.inv(eig[1])@D@np.linalg.inv(eig[1].T)

array([[3.00000000e+09, 8.84847506e-08, 0.00000000e+00],
       [1.46020094e-07, 1.61538462e+09, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.07692308e+08]])

In [140]:
T = np.linalg.inv(eig[1])

In [141]:
T

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

### 2.11

In [142]:
# by multiplying both sides of 2.70 by g_j, we would get definition 2.67

### 2.12

#### a).

In [143]:
g1=np.array([1,0])

In [144]:
g2=np.array([1/np.sqrt(2),1/np.sqrt(2)])

In [145]:
R = 3*g1+4*g2

In [146]:
u = -2*g1+3*g2

In [147]:
R@u

6.707106781186545

#### b).

In [148]:
# a=g1.reshape(2,1)@g2.reshape(1,2)

In [149]:
# inv_a=np.linalg.pinv(a)

In [150]:
# g1_cont=inv_a@g1
# g2_cont=inv_a@g2

In [151]:
# u_cont=-2*(a@g1_cont)+3*(a@g2_cont)=-2*(a@inv_a@g1)+3*(a@inv_a@g2)=u

In [152]:
# R@u_cont=R@u