In [1]:
import numpy as np

### 2.1

In [2]:
# https://gist.github.com/hayesall/25d7ab12dcacf5988f577660c50d0bed

In [3]:
A = np.array([[3, 4, 1],
            [4, 6, 2],
            [1, 2, 3]])

In [4]:
B = np.array([1,2,3])
B=B.reshape(B.shape[0],1)

In [5]:
B.T.shape

(1, 3)

In [6]:
k = 4


In [7]:
C = np.array([[4, 1, -2],
            [1, 8, -1],
            [-2, -1, 6]])

In [8]:
def matrix_chain_order(p):
    """
    Matrix-Chain-Order given a list of integers corresponding to the dimensions
    of each pair of matrices forming a chain.
    :param list p: A list of integers.
    
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print(M)
    {(1, 1): 0, (2, 2): 0, (3, 3): 0, (1, 2): 160, (2, 3): 480, (1, 3): 208}
    >>> print(S)
    {(1, 2): 1, (2, 3): 2, (1, 3): 2}
    """
    s = {}
    m = {}
    n = len(p)
    
    for i in range(1, n):
        m[tuple([i, i])] = 0
    
    for l in range(2, n):
        for i in range(1, n - l + 1):
            j = i + l - 1
            m[tuple([i, j])] = float('inf')
            for k in range(i, j):
                q = m[tuple([i, k])] + m[tuple([k + 1, j])] + (p[i-1] * p[k] * p[j])
                if q < m[tuple([i, j])]:
                    m[tuple([i, j])] = q
                    s[tuple([i, j])] = k
    return m, s


def print_optimal_parens(s, i, j):
    """
    Print the optimal parentheses according to the S-matrix computed by the
    matrix_chain_order function.
    :param dict s: A dictionary of tuples corresponding to the minimum k
                   values from each step of ``matrix_chain_order``.
    :param int i: Starting index.
    :param int j: End index.
    Example (continued from previous function):
    >>> M, S = matrix_chain_order([2, 20, 4, 6])
    >>> print_optimal_parens(S, 1, 3)
    ((A_1A_2)A_3)
    General form:
    
    >>> chain = [2, 20, 4, 6]
    >>> M, S = matrix_chain_order(chain)
    >>> print_optimal_parens(S, 1, len(S) - 1)
    ((A_1A_2)A_3)
    """

    if i == j:
        print("A_{}".format(i), end='')
    else:
        print('(', end='')
        print_optimal_parens(s, i, s[tuple([i, j])])
        print_optimal_parens(s, s[tuple([i, j])] + 1, j)
        print(')', end='')

In [21]:
cha = [B.T, A, k, C, B]
chain = []
const=1
for it in cha:
    if type(it)==type(np.zeros(3)):
        chain.append(it)
    else:
        const*=it

In [24]:
chain

[array([[1, 2, 3]]),
 array([[3, 4, 1],
        [4, 6, 2],
        [1, 2, 3]]),
 array([[ 4,  1, -2],
        [ 1,  8, -1],
        [-2, -1,  6]]),
 array([[1],
        [2],
        [3]])]

In [23]:
const

4

In [11]:
chain_dim=[chain[i].shape[0] for i in range(len(chain)-1)]

In [12]:
chain_dim.append(chain[-1].shape[0])
chain_dim.append(chain[-1].shape[1])

In [13]:
chain_dim

[1, 3, 3, 3, 1]

In [14]:
ch=[chain[i].shape for i in range(len(chain))]

In [15]:
ch

[(1, 3), (3, 3), (3, 3), (3, 1)]

In [16]:
M, S = matrix_chain_order(chain_dim)

In [17]:
M, S

({(1, 1): 0,
  (2, 2): 0,
  (3, 3): 0,
  (4, 4): 0,
  (1, 2): 9,
  (2, 3): 27,
  (3, 4): 9,
  (1, 3): 18,
  (2, 4): 18,
  (1, 4): 21},
 {(1, 2): 1, (2, 3): 2, (3, 4): 3, (1, 3): 2, (2, 4): 2, (1, 4): 1})

In [18]:
print_optimal_parens(S, 1, len(ch))

(A_1(A_2(A_3A_4)))