In [1]:
from sympy import *
import numpy as np
from scipy.linalg import lu_factor, lu_solve

### 3.2

In [2]:
Ds1 = 0.02
Ds2 = 0.005
Ds3 = 0.0035
L1 = 1.3
L2 = 8
L3 = 2.5
Ф1 =20
Ф4 = -15

In [3]:
# R2 = -Ds1/L1*Ф1+(Ds1/L1+Ds2/L2)*Ф2-Ds2/L2*Ф3
# R3 = -Ds2/L2*Ф2+(Ds2/L2+Ds3/L3)*Ф3-Ds3/L3*Ф4

In [4]:
K = np.matrix([[(Ds1/L1+Ds2/L2), -Ds2/L2], 
             [-Ds2/L2, (Ds2/L2+Ds3/L3)]])

In [5]:
F = np.array([Ds1/L1*Ф1,Ds3/L3*Ф4])

In [6]:
lu, piv = lu_factor(K)

In [7]:
ans=lu_solve((lu, piv), F)

In [8]:
ans

array([19.04383068, -4.49264485])

In [9]:
# -D[e]*dC[e]/dx=D[e]*1/L*(-C[e]+C[e+1])

In [10]:
C1=20
C4=-15

In [11]:
-Ds1*1/L1*(-C1+19.04383068)

0.014710297230769241

In [12]:
-Ds2*1/L2*(-19.04383068+(-4.49264485))

0.014710297206249999

In [13]:
-Ds3*1/L3*(4.49264485+C4)

0.01471029721

### 3.4

In [14]:
# R2 = -1/L1*Ф1+(1/L1+1/L2)*Ф2-1/L2*Ф3-Q1*L1/2-Q2*L2/2
# R3 = -1/L2*Ф2+(1/L2+1/L3)*Ф3-1/L3*Ф4-Q2*L2/2-Q3*L3/2
# R4 = -1/L3*Ф3+(1/L3+1/L4)*Ф4-1/L4*Ф5-Q3*L3/2-Q4*L4/2

#### a).

In [15]:
L1=L2=L3=L4=0.5

In [16]:
Q1=Q2=Q3=Q4=4

In [17]:
Ф1=0

In [18]:
Ф5=3

In [19]:
K = np.matrix([[(1/L1+1/L2), -1/L2, 0], 
               [-1/L2, (1/L2+1/L3), -1/L3],
               [0,-1/L3,(1/L3+1/L4)]])

In [20]:
F = np.array([1/L1*Ф1+Q1*L1/2+Q2*L2/2,
              Q2*L2/2+Q3*L3/2,
             1/L4*Ф5+Q3*L3/2+Q4*L4/2])

In [21]:
lu, piv = lu_factor(K)

In [22]:
ans=lu_solve((lu, piv), F)

In [23]:
ans

array([2.25, 3.5 , 3.75])

#### c).

In [24]:
Q1=Q2=Q3=Q4=-3

In [25]:
Ф1=2

In [26]:
Ф5=0.5

In [27]:
K = np.matrix([[(1/L1+1/L2), -1/L2, 0], 
               [-1/L2, (1/L2+1/L3), -1/L3],
               [0,-1/L3,(1/L3+1/L4)]])

In [28]:
F = np.array([1/L1*Ф1+Q1*L1/2+Q2*L2/2,
              Q2*L2/2+Q3*L3/2,
             1/L4*Ф5+Q3*L3/2+Q4*L4/2])

In [29]:
lu, piv = lu_factor(K)

In [30]:
ans=lu_solve((lu, piv), F)

In [31]:
ans

array([ 0.5 , -0.25, -0.25])

### 3.8

In [32]:
EI=2*10**10

In [33]:
D1=D2=D3=D4=EI

In [34]:
L=200

In [35]:
L1=L2=L3=L4=L

In [36]:
P=4*10**6/400*2

In [37]:
P

20000.0

In [38]:
H=800

In [39]:
def M(x,P,H):
    if x<=H/2:
        return P*x/2
    else:
        return P/2*(H-x)

In [40]:
M(0,P,H)

0.0

In [41]:
Q1=-M(0,P,H)

In [42]:
Q2=-M(200,P,H)

In [43]:
Q3=-M(400,P,H)

In [44]:
Q3

-4000000.0

In [45]:
Q4=-M(600,P,H)

In [46]:
Q5=-M(800,P,H)

In [47]:
Ф1=0

In [48]:
Ф5=0

In [49]:
# R2 = -D1/L*Ф1+(D1/L+D2/L)*Ф2-D2/L*Ф3-Q1*L/6-4*Q2*L/6-Q3*L/6
# R3 = -D2/L*Ф2+(D2/L+D3/L)*Ф3-D3/L*Ф4-Q2*L/6-4*Q3*L/6-Q4*L/6
# R4 = -D3/L*Ф3+(D3/L+D4/L)*Ф4-D4/L*Ф5-Q3*L/6-4*Q4*L/6-Q5*L/6

In [50]:
K = np.matrix([[(D1/L+D2/L), -D2/L, 0], 
               [-D2/L, (D2/L+D3/L), -D3/L],
               [0,-D3/L,(D3/L+D4/L)]])

In [51]:
F = np.array([(D1/L*Ф1+Q1*L/6+4*Q2*L/6+Q3*L/6),
              (Q2*L/6+4*Q3*L/6+Q4*L/6),
             (D4/L*Ф5+Q3*L/6+4*Q4*L/6+Q5*L/6)])

In [52]:
lu, piv = lu_factor(K)

In [53]:
ans=lu_solve((lu, piv), F)

In [54]:
ans

array([ -7.33333333, -10.66666667,  -7.33333333])