In [1]:
from sympy import *
import math
import numpy as np

### 24.1

In [2]:
Ri=1
Zi=1
Rj=3
Zj=1
Rk=3
Zk=4

In [3]:
def B(Xi, Yi, Xj, Yj, Xk, Yk, x, y):
    A=0.5*np.linalg.det(np.array([[1,Xi,Yi], [1,Xj,Yj], [1,Xk,Yk]]))
    ai=Xj*Yk-Xk*Yj
    aj=Xk*Yi-Xi*Yk
    ak=Xi*Yj-Xj*Yi
    bi=Yj-Yk
    bj=Yk-Yi
    bk=Yi-Yj
    ci=Xk-Xj
    cj=Xi-Xk
    ck=Xj-Xi
    Ni=(ai+bi*x+ci*y)/(2*A)
    Nj=(aj+bj*x+cj*y)/(2*A)
    Nk=(ak+bk*x+ck*y)/(2*A)
    return 1/(2*A)*np.matrix([[bi,0,bj,0,bk,0],
                      [2*A*Ni/x,0,2*A*Nj/x,0,2*A*Nk/x,0],
                      [0,ci,0,cj,0,ck],
                      [ci,bi,cj,bj,ck,bk]])

In [4]:
r=(Ri+Rj+Rk)/3
z=(Zi+Zj+Zk)/3

In [5]:
B(Ri, Zi, Rj, Zj, Rk, Zk, r, z)

matrix([[-0.5       ,  0.        ,  0.5       ,  0.        ,  0.        ,
          0.        ],
        [ 0.14285714,  0.        ,  0.14285714,  0.        ,  0.14285714,
          0.        ],
        [ 0.        ,  0.        ,  0.        , -0.33333333,  0.        ,
          0.33333333],
        [ 0.        , -0.5       , -0.33333333,  0.5       ,  0.33333333,
          0.        ]])

### 24.3

In [6]:
Ri=2
Zi=4
Rj=4
Zj=4
Rk=3
Zk=6

In [7]:
r=(Ri+Rj+Rk)/3
z=(Zi+Zj+Zk)/3

In [8]:
B(Ri, Zi, Rj, Zj, Rk, Zk, r, z)

matrix([[-0.5       ,  0.        ,  0.5       ,  0.        ,  0.        ,
          0.        ],
        [ 0.11111111,  0.        ,  0.11111111,  0.        ,  0.11111111,
          0.        ],
        [ 0.        , -0.25      ,  0.        , -0.25      ,  0.        ,
          0.5       ],
        [-0.25      , -0.5       , -0.25      ,  0.5       ,  0.5       ,
          0.        ]])

In [9]:
# TODO - the answer is not the same as in the book (by a bit)

### 24.7

In [10]:
alp=10e-6

In [11]:
dT=15

In [12]:
E=20e6

In [13]:
mu=1/4

In [14]:
Ri=6
Zi=7
Rj=8
Zj=7
Rk=9
Zk=10

In [15]:
d=(1-mu)/(1-2*mu)

In [16]:
b=mu/(1-2*mu)

In [17]:
D=E/(1+mu)*np.matrix([[d,b,b,0],[b,d,b,0],[b,b,d,0],[0,0,0,1/2]])

In [18]:
r=(Ri+Rj+Rk)/3
z=(Zi+Zj+Zk)/3

In [19]:
ep=np.matrix([[alp*dT,alp*dT,alp*dT,0]])

In [20]:
A=0.5*np.linalg.det(np.array([[1,Ri,Zi], [1,Rj,Zj], [1,Rk,Zk]]))

In [21]:
2*np.pi*r*A*np.dot(np.dot(B(Ri, Zi, Rj, Zj, Rk, Zk, r, z).T, D), ep.T)

matrix([[-395840.67435231],
        [ 144513.26206513],
        [ 471238.89803847],
        [-433539.78619539],
        [  37699.11184308],
        [ 289026.52413026]])

In [22]:
# TODO - the answer is not the same as in the book

### 24.8

In [23]:
Ri=2
Zi=4
Rj=4
Zj=4
Rk=3
Zk=6

In [24]:
r=(Ri+Rj+Rk)/3
z=(Zi+Zj+Zk)/3

In [25]:
Z=10
R=0

In [26]:
A=0.5*np.linalg.det(np.array([[1,Ri,Zi], [1,Rj,Zj], [1,Rk,Zk]]))

In [27]:
2*np.pi*A/12*np.matrix([[(Ri+3*r)*R],
                        [(Ri+3*r)*Z],
                        [(Rj+3*r)*R],
                        [(Rj+3*r)*Z],
                        [(Rk+3*r)*R],
                        [(Rk+3*r)*Z]])

matrix([[  0.        ],
        [115.19173063],
        [  0.        ],
        [136.13568166],
        [  0.        ],
        [125.66370614]])

### 24.11

In [28]:
R2=5
R3=9
R4=13

In [29]:
pz=-300

In [30]:
L=5

In [31]:
P2=2*np.pi*L/6*(2*R2+R3)*pz
P3_1=2*np.pi*L/6*(R2+2*R3)*pz
P3_2=2*np.pi*L/6*(2*R3+R4)*pz
P4=2*np.pi*L/6*(R3+2*R4)*pz

In [32]:
P2, P3_1+P3_2, P4

(-29845.130209103037, -84823.00164692441, -54977.871437821384)

### 24.12

In [33]:
pi = Symbol('pi')

In [34]:
L_ = Symbol('L_')

In [35]:
p0 = Symbol('p0')

In [36]:
l=Symbol('l')

In [37]:
pr = 0

In [38]:
pz = p0*l

In [39]:
L1=0
L2=Symbol('L2')
L3=Symbol('L3')
R_i=Symbol('R_i')
R_j=Symbol('R_j')
R_k=Symbol('R_k')

In [40]:
def L(a,b,c):
    return math.factorial(a)*math.factorial(b)*math.factorial(c)/math.factorial(a+b+c+2)

In [41]:
r=R_i*L1+R_j*L2+R_k*L3

In [42]:
N=Matrix([[0,0,r*L2,0,r*L3,0],[0,0,0,r*L2,0,r*L3]])

In [43]:
np.dot(N.T,  Matrix([pr,pz]))

array([[0],
       [0],
       [0],
       [L2*l*p0*(L2*R_j + L3*R_k)],
       [0],
       [L3*l*p0*(L2*R_j + L3*R_k)]], dtype=object)

In [44]:
2*pi*L_*integrate(Matrix(np.dot(N.T,  Matrix([pr,pz]))), (l, 0, 1))

Matrix([
[                                        0],
[                                        0],
[                                        0],
[2*L_*pi*(L2**2*R_j*p0/2 + L2*L3*R_k*p0/2)],
[                                        0],
[2*L_*pi*(L2*L3*R_j*p0/2 + L3**2*R_k*p0/2)]])

In [45]:
L(0,2,0), L(0,1,1), L(0,0,2)

(0.08333333333333333, 0.041666666666666664, 0.08333333333333333)

In [46]:
# not sure about this task
# TODO - the answer is not the same as in the book

### 24.15

In [47]:
dT=0
alp=10e-6
E=20e6
mu=1/4

In [48]:
Ri=6
Zi=7
Rj=8
Zj=7
Rk=9
Zk=10

In [49]:
d=(1-mu)/(1-2*mu)

In [50]:
b=mu/(1-2*mu)

In [51]:
D=E/(1+mu)*np.matrix([[d,b,b,0],[b,d,b,0],[b,b,d,0],[0,0,0,1/2]])

In [52]:
r=(Ri+Rj+Rk)/3
z=(Zi+Zj+Zk)/3

In [53]:
B_=B(Ri, Zi, Rj, Zj, Rk, Zk, r, z)

In [54]:
U=np.matrix([[0.005,0,0.003,0.002,0.006,0.001]])

In [55]:
np.dot(np.dot(D,B_),U.T)

matrix([[-24463.76811594],
        [  1275.36231884],
        [-19130.43478261],
        [ 18666.66666667]])