In [1]:
from sympy import *
import math
import numpy as np

### 14.1

In [2]:
D=4
lambda_=12
q=5
dt=1
L=2

In [3]:
def elementTimeStiffness(lambda_, L):
    return lambda_*L/2*np.matrix([[1, 0], [0, 1]])

In [4]:
def elementStiffness(D, L):
    return D/L*np.matrix([[1, -1], [-1, 1]])

In [5]:
e = 2
n = e+1

In [6]:
elem=[]    
for i in range(e):
    P_=[i,i+1]
    elem.append(P_)
elem=np.array(elem) 

In [7]:
K=np.zeros((n,n))   
F=np.zeros((n,1))  
C=np.zeros((n,n)) 

for i in range(e):
    node1 = elem[i,0]
    node2 = elem[i,1]
    Ke = elementStiffness(D, L)
    Ce = elementTimeStiffness(lambda_, L)
    K[node1:node2+1,node1:node2+1] = K[node1:node2+1,node1:node2+1] + Ke
    C[node1:node2+1,node1:node2+1] = C[node1:node2+1,node1:node2+1] + Ce

F[0] = F[0] + q
   
A=C+dt/2*K
P=C-dt/2*K
Co=dt/2

Fa=Fb=F

ans=np.linalg.lstsq(A, Co*(Fa+Fb), rcond=None)[0]

In [8]:
ans

array([[0.38576007],
       [0.01488095],
       [0.00114469]])

In [9]:
ans2 = np.linalg.lstsq(A, np.dot(P, ans)+Co*(Fa+Fb), rcond=None)[0]

In [10]:
ans2

array([[0.71642414],
       [0.05527211],
       [0.00636497]])

### 14.4

In [11]:
D=2
lambda_=6
dt=1
L=2

In [12]:
e = 4
n = e+1

In [13]:
def elementTimeStiffnessC(lambda_, L):
    return lambda_*L/6*np.matrix([[2, 1], 
                                  [1, 2]])

In [14]:
elem=[]    
for i in range(e):
    P_=[i,i+1]
    elem.append(P_)
elem=np.array(elem) 

In [15]:
K=np.zeros((n,n))   
C=np.zeros((n,n)) 
F=np.zeros((n,1)) 

for i in range(e):
    node1 = elem[i,0]
    node2 = elem[i,1]
    Ke = elementStiffness(D, L)
    Ce = elementTimeStiffnessC(lambda_, L)
    K[node1:node2+1,node1:node2+1] = K[node1:node2+1,node1:node2+1] + Ke
    C[node1:node2+1,node1:node2+1] = C[node1:node2+1,node1:node2+1] + Ce

    
bc=np.array([[0,4], [10,10]]).T

nd, nd=K.shape
fdof=np.array([i for i in range(nd)]).T
d=np.zeros(shape=(len(fdof),))

pdof=bc[:,0].astype(int)
dp=bc[:,1]
fdof=np.delete(fdof, pdof, 0) 

In [16]:
A=C+2*dt/3*K
P=C-dt/3*K

In [17]:
A[fdof,:][:,fdof]

array([[9.33333333, 1.33333333, 0.        ],
       [1.33333333, 9.33333333, 1.33333333],
       [0.        , 1.33333333, 9.33333333]])

In [18]:
P[fdof,:][:,fdof]

array([[7.33333333, 2.33333333, 0.        ],
       [2.33333333, 7.33333333, 2.33333333],
       [0.        , 2.33333333, 7.33333333]])

In [19]:
Fa=Fb=(F[fdof].T-np.dot(K[fdof,:][:,pdof],dp.T)).T

In [20]:
dt/3*(Fa+2*Fb)

array([[10.],
       [ 0.],
       [10.]])

In [21]:
# TODO - the answer is not the same as in the book

### 14.6

In [22]:
D=2
lambda_=6
dt=1
L=2

In [23]:
e = 4
n = e+1

In [24]:
elem=[]    
for i in range(e):
    P_=[i,i+1]
    elem.append(P_)
elem=np.array(elem) 

In [25]:
K=np.zeros((n,n))   
C=np.zeros((n,n)) 
F=np.zeros((n,1)) 

for i in range(e):
    node1 = elem[i,0]
    node2 = elem[i,1]
    Ke = elementStiffness(D, L)
    Ce = elementTimeStiffness(lambda_, L)
    K[node1:node2+1,node1:node2+1] = K[node1:node2+1,node1:node2+1] + Ke
    C[node1:node2+1,node1:node2+1] = C[node1:node2+1,node1:node2+1] + Ce

    
bc=np.array([[0,4], [10,10]]).T

nd, nd=K.shape
fdof=np.array([i for i in range(nd)]).T
d=np.zeros(shape=(len(fdof),))

pdof=bc[:,0].astype(int)
dp=bc[:,1]
fdof=np.delete(fdof, pdof, 0) 

In [26]:
A=C
P=C-dt*K

In [27]:
C1=A[fdof,:][:,fdof]

In [28]:
C2=P[fdof,:][:,fdof]

In [29]:
Fa=Fb=(F[fdof].T-np.dot(K[fdof,:][:,pdof],dp.T)).T

In [30]:
C3=dt*Fa

In [31]:
ans = np.linalg.lstsq(C1, np.dot(C2, np.array([50,50,50]).reshape(3,1))+C3, rcond=None)[0]

In [32]:
ans

array([[46.66666667],
       [50.        ],
       [46.66666667]])

In [33]:
ans2 = np.linalg.lstsq(C1, np.dot(C2, ans)+C3, rcond=None)[0]

In [34]:
ans2

array([[43.88888889],
       [49.44444444],
       [43.88888889]])

### 14.8

In [35]:
D=3
lambda_=4
dt=1
L=3

In [36]:
e = 4
n = e+1

In [37]:
elem=[]    
for i in range(e):
    P_=[i,i+1]
    elem.append(P_)
elem=np.array(elem) 

In [38]:
K=np.zeros((n,n))   
C=np.zeros((n,n)) 
F=np.zeros((n,1)) 

for i in range(e):
    node1 = elem[i,0]
    node2 = elem[i,1]
    Ke = elementStiffness(D, L)
    Ce = elementTimeStiffnessC(lambda_, L)
    K[node1:node2+1,node1:node2+1] = K[node1:node2+1,node1:node2+1] + Ke
    C[node1:node2+1,node1:node2+1] = C[node1:node2+1,node1:node2+1] + Ce

    
bc=np.array([[0], [5]]).T

nd, nd=K.shape
fdof=np.array([i for i in range(nd)]).T
d=np.zeros(shape=(len(fdof),))

pdof=bc[:,0].astype(int)
dp=bc[:,1]
fdof=np.delete(fdof, pdof, 0) 

In [39]:
A=C
P=C-dt*K

In [40]:
A[fdof,:][:,fdof]

array([[8., 2., 0., 0.],
       [2., 8., 2., 0.],
       [0., 2., 8., 2.],
       [0., 0., 2., 4.]])

In [41]:
P[fdof,:][:,fdof]

array([[6., 3., 0., 0.],
       [3., 6., 3., 0.],
       [0., 3., 6., 3.],
       [0., 0., 3., 3.]])

In [42]:
Fa=(F[fdof].T-np.dot(K[fdof,:][:,pdof],dp.T)).T

In [43]:
dt*Fa

array([[5.],
       [0.],
       [0.],
       [0.]])

### 14.10

In [44]:
D=3
lambda_=4
dt=1
L=3

In [45]:
e = 4
n = e+1

In [46]:
elem=[]    
for i in range(e):
    P_=[i,i+1]
    elem.append(P_)
elem=np.array(elem) 

In [47]:
K=np.zeros((n,n))   
C=np.zeros((n,n)) 
F=np.zeros((n,1)) 

for i in range(e):
    node1 = elem[i,0]
    node2 = elem[i,1]
    Ke = elementStiffness(D, L)
    Ce = elementTimeStiffness(lambda_, L)
    K[node1:node2+1,node1:node2+1] = K[node1:node2+1,node1:node2+1] + Ke
    C[node1:node2+1,node1:node2+1] = C[node1:node2+1,node1:node2+1] + Ce

    
bc=np.array([[0], [5]]).T

nd, nd=K.shape
fdof=np.array([i for i in range(nd)]).T
d=np.zeros(shape=(len(fdof),))

pdof=bc[:,0].astype(int)
dp=bc[:,1]
fdof=np.delete(fdof, pdof, 0) 

In [48]:
A=C
P=C-dt*K

In [49]:
C1=A[fdof,:][:,fdof]

In [50]:
C2=P[fdof,:][:,fdof]

In [51]:
Fa=(F[fdof].T-np.dot(K[fdof,:][:,pdof],dp.T)).T

In [52]:
C3=dt*Fa

In [53]:
ans = np.linalg.lstsq(C1, np.dot(C2, np.array([30,30,30,30]).reshape(4,1))+C3, rcond=None)[0]

In [54]:
ans

array([[27.91666667],
       [30.        ],
       [30.        ],
       [30.        ]])

In [55]:
ans2 = np.linalg.lstsq(C1, np.dot(C2, ans)+C3, rcond=None)[0]

In [56]:
ans2

array([[26.18055556],
       [29.82638889],
       [30.        ],
       [30.        ]])

In [57]:
# TODO - the answer is not the same as in the book

### 14.12

In [58]:
D=4
lambda_=12
q=5
dt=1
L=2

In [59]:
e = 2
n = e+1

In [60]:
elem=[]    
for i in range(e):
    P_=[i,i+1]
    elem.append(P_)
elem=np.array(elem) 

In [61]:
K=np.zeros((n,n))   
F=np.zeros((n,1))  
C=np.zeros((n,n)) 

for i in range(e):
    node1 = elem[i,0]
    node2 = elem[i,1]
    Ke = elementStiffness(D, L)
    Ce = elementTimeStiffness(lambda_, L)
    K[node1:node2+1,node1:node2+1] = K[node1:node2+1,node1:node2+1] + Ke
    C[node1:node2+1,node1:node2+1] = C[node1:node2+1,node1:node2+1] + Ce

F[0] = F[0] + q
   
    
A=C+2*dt/3*K
P=C-dt/3*K



bc=np.array([[0], [10]]).T

nd, nd=K.shape
fdof=np.array([i for i in range(nd)]).T
d=np.zeros(shape=(len(fdof),))

pdof=bc[:,0].astype(int)
dp=bc[:,1]
fdof=np.delete(fdof, pdof, 0) 



C1=A[fdof,:][:,fdof]
C2=P[fdof,:][:,fdof]
Fa=Fb=(F[fdof].T-np.dot(K[fdof,:][:,pdof],dp.T)).T
Co=dt/3*(Fa+2*Fb)

ans=np.linalg.lstsq(C1, Co, rcond=None)[0]

In [62]:
ans

array([[0.75376884],
       [0.07537688]])

In [63]:
ans2 = np.linalg.lstsq(C1, np.dot(C2, ans)+Co, rcond=None)[0]

In [64]:
ans2

array([[1.40469938],
       [0.24222873]])

In [65]:
# [10, 1.40469938, 0.24222873]

In [66]:
np.linalg.lstsq(C1, np.dot(C2, ans2)+Co, rcond=None)[0]

array([[1.97372528],
       [0.47350192]])