In [1]:
from sympy import *
import math
import numpy as np

### 7.1

#### a)

In [2]:
s=Symbol('s')
t=Symbol('t')
Q=Symbol('Q')
a=Symbol('a')
b=Symbol('b')

In [3]:
Ni=1-s/(2*b)-t/(2*a)+s*t/(4*a*b)

In [4]:
Q*integrate(Ni, (s,0,2*b),(t,0,2*a))

Q*a*b

In [5]:
# Q*A/4

### 7.2

#### a)

In [6]:
G=Symbol('G')

In [7]:
Nj=s/(2*b)-s*t/(4*a*b)

In [8]:
G*integrate(Ni*Nj, (s,0,2*b),(t,0,2*a))

2*G*a*b/9

In [9]:
# 2*G*A/36

### 7.4

In [10]:
Q_i=Symbol('Q_i')
Q_j=Symbol('Q_j')
Q_k=Symbol('Q_k')
L_i=Symbol('L_i')
L_j=Symbol('L_j')
L_k=Symbol('L_k')

In [11]:
Ni=L_i

In [12]:
Nj=L_j

In [13]:
Nk=L_k

In [14]:
Q=Ni*Q_i+Nj*Q_j+Nk*Q_k

In [15]:
N= Matrix([Ni,Nj,Nk])

In [16]:
Q*N

Matrix([
[L_i*(L_i*Q_i + L_j*Q_j + L_k*Q_k)],
[L_j*(L_i*Q_i + L_j*Q_j + L_k*Q_k)],
[L_k*(L_i*Q_i + L_j*Q_j + L_k*Q_k)]])

In [17]:
A=Symbol('A')

In [18]:
def integral(a,b,c,A):
    return 2*A*math.factorial(a)*math.factorial(b)*math.factorial(c)/math.factorial(a+b+c+2)

In [19]:
[integral(2,0,0,A)*Q_i+integral(1,1,0,A)*Q_j+integral(1,0,1,A)*Q_k,
    integral(1,1,0,A)*Q_i+integral(0,2,0,A)*Q_j+integral(0,1,1,A)*Q_k,
    integral(1,0,1,A)*Q_i+integral(0,1,1,A)*Q_j+integral(0,0,2,A)*Q_k]

[A*Q_i/6 + A*Q_j/12 + A*Q_k/12,
 A*Q_i/12 + A*Q_j/6 + A*Q_k/12,
 A*Q_i/12 + A*Q_j/12 + A*Q_k/6]

### 7.9

#### a)

In [20]:
Xi=0.13
Yi=0.01
Xj=0.25
Yj=0.06
Xk=0.13
Yk=0.13

In [21]:
bi=Yj-Yk
bj=Yk-Yi
bk=Yi-Yj
ci=Xk-Xj
cj=Xi-Xk
ck=Xj-Xi

In [22]:
Dx=Dy=1

In [23]:
G=4

In [24]:
Q=5

In [25]:
A=0.5*np.linalg.det(
    np.matrix([[1,Xi,Yi],
              [1,Xj,Yj],
              [1,Xk,Yk]]))

In [26]:
A

0.007200000000000001

In [27]:
kd_1=Dx/(4*A)*Matrix([[bi**2,bi*bj,bi*bk],
                      [bi*bj,bj**2,bj*bk],
                      [bi*bk,bj*bk,bk**2]])
kd_2=Dy/(4*A)*Matrix([[ci**2,ci*cj,ci*ck],
                      [ci*cj,cj**2,cj*ck],
                      [ci*ck,cj*ck,ck**2]])

In [28]:
kd=kd_1+kd_2

In [29]:
kd

Matrix([
[ 0.670138888888889, -0.291666666666667, -0.378472222222222],
[-0.291666666666667,                0.5, -0.208333333333333],
[-0.378472222222222, -0.208333333333333,  0.586805555555556]])

In [30]:
kg=G*A/12*Matrix([[2,1,1],
                  [1,2,1],
                  [1,1,2]])

In [31]:
kg

Matrix([
[0.0048, 0.0024, 0.0024],
[0.0024, 0.0048, 0.0024],
[0.0024, 0.0024, 0.0048]])

In [32]:
k=kd+kg

In [33]:
k

Matrix([
[ 0.674938888888889, -0.289266666666667, -0.376072222222222],
[-0.289266666666667,             0.5048, -0.205933333333333],
[-0.376072222222222, -0.205933333333333,  0.591605555555556]])

In [34]:
f=Q*A/3*Matrix([1,1,1])

In [35]:
f

Matrix([
[0.012],
[0.012],
[0.012]])

In [36]:
# TODO - the answer is not the same as in the book

### 7.10

#### b)

In [37]:
Dx=Dy=0.5

In [38]:
G=10

In [39]:
Q=40

In [40]:
Xi=0.25

In [41]:
Yi=0.18

In [42]:
Xj=0.31

In [43]:
Ym=0.25

In [44]:
A=(Xj-Xi)*(Ym-Yi)

In [45]:
kg=G*A/36*np.matrix([[4,2,1,2],
                  [2,4,2,1],
                  [1,2,4,2],
                  [2,1,2,4]])

In [46]:
kg

matrix([[0.00466667, 0.00233333, 0.00116667, 0.00233333],
        [0.00233333, 0.00466667, 0.00233333, 0.00116667],
        [0.00116667, 0.00233333, 0.00466667, 0.00233333],
        [0.00233333, 0.00116667, 0.00233333, 0.00466667]])

In [47]:
kd_1=Dx*(Ym-Yi)/(6*(Xj-Xi))*np.matrix([  [2,-2,-1,1],
                                      [-2,2,1,-1],
                                      [-1,1,2,-2],
                                      [1,-1,-2,2]])

In [48]:
kd_2=Dy*(Xj-Xi)/(6*(Ym-Yi))*np.matrix([  [2,1,-1,-2],
                                      [1,2,-2,-1],
                                      [-1,-2,2,1],
                                      [-2,-1,1,2]])

In [49]:
k=kg+kd_1+kd_2

In [50]:
k

matrix([[ 0.34196825, -0.12068254, -0.16748413, -0.04330159],
        [-0.12068254,  0.34196825, -0.04330159, -0.16748413],
        [-0.16748413, -0.04330159,  0.34196825, -0.12068254],
        [-0.04330159, -0.16748413, -0.12068254,  0.34196825]])

In [51]:
f=Q*A/4*np.array([1,1,1,1])

In [52]:
f

array([0.042, 0.042, 0.042, 0.042])