In [1]:
from sympy import *
import math
import numpy as np

### 23.1

In [2]:
t=2

In [3]:
D=1e6*np.matrix([[16,4,0],[4,16,0],[0,0,6]])

In [4]:
Xi=2
Yi=0
Xj=1
Yj=1
Xk=1
Yk=0

In [5]:
U11=0.003
U12=0
U21=0.001
U22=-0.0003
U31=0.0015
U32=0

In [6]:
A=0.5*np.linalg.det(np.array([[1,Xi,Yi],
              [1,Xj,Yj],
              [1,Xk,Yk]]))

In [7]:
def B(Xi,Yi,Xj,Yj,Xk,Yk,A):
    
    bi=Yj-Yk
    bj=Yk-Yi
    bk=Yi-Yj
    ci=Xk-Xj
    cj=Xi-Xk
    ck=Xj-Xi
    return 1/(2*A)*np.matrix([[bi,0,bj,0,bk,0],
                              [0,ci,0,cj,0,ck],
                              [ci,bi,cj,bj,ck,bk]])

In [8]:
B0=B(Xi,Yi,Xj,Yj,Xk,Yk,A)

In [9]:
k=np.dot(np.dot(B0.T,D),B0)*t*A

In [10]:
k

matrix([[ 16000000.,         0.,         0.,   4000000., -16000000.,
          -4000000.],
        [        0.,   6000000.,   6000000.,         0.,  -6000000.,
          -6000000.],
        [        0.,   6000000.,   6000000.,         0.,  -6000000.,
          -6000000.],
        [  4000000.,         0.,         0.,  16000000.,  -4000000.,
         -16000000.],
        [-16000000.,  -6000000.,  -6000000.,  -4000000.,  22000000.,
          10000000.],
        [ -4000000.,  -6000000.,  -6000000., -16000000.,  10000000.,
          22000000.]])

In [11]:
U=np.array([U11,U12,U21,U22,U31,U32]).reshape(6,1)

In [12]:
S=np.dot(D,np.dot(B0,U))

In [13]:
S

matrix([[22800.],
        [ 1200.],
        [-3000.]])

### 23.3

In [14]:
Xi=6.6
Yi=3
Xj=7.9
Yj=4
Xk=6
Yk=4

In [15]:
U11=0.007
U12=-0.001
U21=0.006
U22=-0.0015
U31=0.006
U32=-0.0018

In [16]:
A=0.5*np.linalg.det(np.array([[1,Xi,Yi],
              [1,Xj,Yj],
              [1,Xk,Yk]]))

In [17]:
B0=B(Xi,Yi,Xj,Yj,Xk,Yk,A)

In [18]:
k=np.dot(np.dot(B0.T,D),B0)*t*A

In [19]:
k

matrix([[ 11400000.        ,         0.        ,  -3600000.        ,
          -6000000.        ,  -7800000.00000001,   6000000.        ],
        [        0.        ,  30400000.00000001,  -4000000.        ,
          -9600000.        ,   4000000.        , -20800000.00000002],
        [ -3600000.        ,  -4000000.        ,   9557894.7368421 ,
           3157894.7368421 ,  -5957894.7368421 ,    842105.2631579 ],
        [ -6000000.        ,  -9600000.        ,   3157894.7368421 ,
           6189473.68421052,   2842105.2631579 ,   3410526.31578947],
        [ -7800000.00000001,   4000000.        ,  -5957894.7368421 ,
           2842105.2631579 ,  13757894.73684211,  -6842105.2631579 ],
        [  6000000.        , -20800000.00000001,    842105.2631579 ,
           3410526.31578947,  -6842105.2631579 ,  17389473.68421054]])

In [20]:
U=np.array([U11,U12,U21,U22,U31,U32]).reshape(6,1)

In [21]:
S=np.dot(D,np.dot(B0,U))

In [22]:
S

matrix([[ -2821.05263158],
        [-11284.21052632],
        [ -5052.63157895]])

### 23.5

In [23]:
Xi=11
Yi=2
Xj=10
Yj=1.8
Xk=10
Yk=1.5

In [24]:
U11=0.016
U12=-0.0008
U21=0.015
U22=-0.0006
U31=0.014
U32=-0.0004

In [25]:
A=0.5*np.linalg.det(np.array([[1,Xi,Yi],
              [1,Xj,Yj],
              [1,Xk,Yk]]))

In [26]:
B0=B(Xi,Yi,Xj,Yj,Xk,Yk,A)

In [27]:
k=np.dot(np.dot(B0.T,D),B0)*t*A

In [28]:
k

matrix([[  4800000.        ,         0.        ,  -8000000.        ,
           4000000.        ,   3200000.        ,  -4000000.        ],
        [        0.        ,   1800000.        ,   6000000.        ,
          -3000000.        ,  -6000000.        ,   1200000.        ],
        [ -8000000.        ,   6000000.        ,  33333333.33333333,
         -16666666.66666667, -25333333.33333333,  10666666.66666666],
        [  4000000.        ,  -3000000.        , -16666666.66666667,
          58333333.33333333,  12666666.66666667, -55333333.33333332],
        [  3200000.        ,  -6000000.        , -25333333.33333333,
          12666666.66666667,  22133333.33333333,  -6666666.66666667],
        [ -4000000.        ,   1200000.        ,  10666666.66666666,
         -55333333.33333332,  -6666666.66666667,  54133333.33333332]])

In [29]:
U=np.array([U11,U12,U21,U22,U31,U32]).reshape(6,1)

In [30]:
S=np.dot(D,np.dot(B0,U))

In [31]:
S

matrix([[ 2666.66666667],
        [-9333.33333333],
        [19600.        ]])

In [32]:
# TODO - the answer is not the same as in the book (by a bit)

### 23.8

In [33]:
Xi=0
Yi=20
Xj=10
Yj=30
Xk=0
Yk=30

In [34]:
U11=0
U12=-0.006
U21=-0.0006
U22=0.007
U31=0
U32=-0.0096

In [35]:
A=0.5*np.linalg.det(np.array([[1,Xi,Yi],
              [1,Xj,Yj],
              [1,Xk,Yk]]))

In [36]:
B0=B(Xi,Yi,Xj,Yj,Xk,Yk,A)

In [37]:
k=np.dot(np.dot(B0.T,D),B0)*t*A

In [38]:
k

matrix([[  6000000.        ,         0.        ,         0.        ,
          -6000000.        ,  -6000000.        ,   6000000.        ],
        [        0.        ,  15999999.99999999,  -4000000.        ,
                 0.        ,   4000000.        , -15999999.99999999],
        [        0.        ,  -4000000.        ,  15999999.99999999,
                 0.        , -15999999.99999999,   4000000.        ],
        [ -6000000.        ,         0.        ,         0.        ,
           6000000.        ,   6000000.        ,  -6000000.        ],
        [ -6000000.        ,   4000000.        , -15999999.99999999,
           6000000.        ,  21999999.99999999,  -9999999.99999999],
        [  6000000.        , -15999999.99999999,   4000000.        ,
          -6000000.        ,  -9999999.99999999,  21999999.99999999]])

In [39]:
U=np.array([U11,U12,U21,U22,U31,U32]).reshape(6,1)

In [40]:
S=np.dot(D,np.dot(B0,U))

In [41]:
S

matrix([[-2400.],
        [-6000.],
        [ 9960.]])

### 23.11

In [42]:
t = Symbol('t')

In [43]:
L = Symbol('L')

In [44]:
l = Symbol('l')

In [45]:
p0 = Symbol('p0')

In [46]:
px = p0*l

In [47]:
py = 0

In [48]:
I = Matrix([0,0,(1-l)*px,(1-l)*py,l*px,l*py])

In [49]:
L*t*integrate(I, (l, 0, 1))

Matrix([
[       0],
[       0],
[L*p0*t/6],
[       0],
[L*p0*t/3],
[       0]])

In [50]:
# TODO - the answer is not the same as in the book